<div class="field skype required">
    <label class="label" for="skype">
      <span><?= $block->escapeHtml(__('Skype Account')) ?></span>
    </label>
    <div class="control">
       <input type="text" name="skype" id="skype" value="" title="<?= $block->escapeHtmlAttr(__('Skype Account')) ?>" class="input-text" data-validate="{required:true}">
    </div>
</div>
<div class="field skype required">
    <label class="label" for="address">
      <span><?= $block->escapeHtml(__('Address')) ?></span>
    </label>
    <div class="control">
       <input type="text" name="address" id="address" value="" title="<?= $block->escapeHtmlAttr(__('Address')) ?>" class="input-text" data-validate="{required:true}">
    </div>
</div>

